config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'employers/show'

  get 'bootcamps/show'

  resources :jobs
  resources :pages
  devise_for :users
  devise_for :bootcamps
  resources :bootcamps
  devise_for :employers
  resources :employers
  resources :users

  root to: 'pages#home'

  get 'jobs' => 'jobs#index'
  get 'post_job' => 'jobs#new'
  get 'about' => 'pages#about'
  get 'suggestions' => 'pages#suggestions'
  get 'user_profile' => 'user#show'
  get 'bootcamp_profile' => 'bootcamps#show'
  get 'employer_profile' => 'employer#show'

  devise_scope :user do
    get "user_signup", to: "devise/registrations#new"
    get "user_login", to: "devise/sessions#new"
    get "user_logout", to: "devise/sessions#destroy"

    get "bootcamp_signup", to: "devise/registrations#new"
    get "bootcamp_login", to: "devise/sessions#new"
    get "bootcamp_logout", to: "devise/sessions#destroy"

    get "employer_signup", to: "devise/registrations#new"
    get "employer_login", to: "devise/sessions#new"
    get "employer_logout", to: "devise/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'carrierwave'
  require 'carrierwave/orm/activerecord'
end

app/models/bootcamp.rb
class Bootcamp < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users
end

app/models/employer.rb
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :employer

  mount_uploader :logo, LogoUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bootcamps_controller.rb
class BootcampsController < ApplicationController
  def show
    @bootcamp = Bootcamp.find(params[:id])
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def show
    @employer = Employer.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  before_action do
    if current_user != nil
     authenticate_user!
   elsif current_bootcamp != nil
     authenticate_bootcamp!
   else
     authenticate_employer!
   end
  end


  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company_name, :location, :company_info, :company_size, :industry, :job_info, :logo, :employer_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def suggestions
  end

  def profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootcamps_helper.rb
module BootcampsHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bootcamps/show.html.erb
<h1>Bootcamps#show</h1>
<p>Find me in app/views/bootcamps/show.html.erb</p>


<%= @bootcamp.email %>

app/views/employers/show.html.erb
<h1>Employers#show</h1>
<p>Find me in app/views/employers/show.html.erb</p>


<%= current_employer.id %>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :company_name %>
    <%= f.input :location %>
    <%= f.input :company_info %>
    <%= f.input :job_info %>
    <%= f.input :company_size %>
    <%= f.input :industry %>
    <%= f.file_field :logo %>
    <%= f.hidden_field :employer_id, :value=>current_employer.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>
  <h1>Jobs Page</h1>

  <% @jobs.each do |job| %>
      <div class="job_list">
        <div class="company_logo_container"><%=image_tag job.logo_url.to_s, :class => 'company_logo'%></div>
        <div class="job_list_info">
          <h3><%=job.title%></h3>
          <h5><%=job.company_name%></h5>
          <h5><%=job.location%></h5>
          <%= link_to "See More", job, class:"btn btn-primary btn-sm" %>
        </div>
      </div>
  <%end%>

</div>

app/views/jobs/new.html.erb
<div class="container">
  <h1>New Job</h1>

  <%= render 'form', job: @job %>

  <%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="job_info">
    <div class="company_logo_container"><%=image_tag @job.logo_url.to_s, :class => 'company_logo'%></div>
    <div class="job_list_info">
      <h3><%=@job.title%></h3>
      <h5><%=@job.company_name%></h5>
      <h5><%=@job.location%></h5>
    </div>

    <div class="job_info">
      <h3>About <%=@job.company_name%></h3>
      <p><%=@job.company_info%></p>
    </div>

    <div class="job_info">
      <h3>About Position</h3>
      <p><%=@job.job_info%></p>
    </div>
  </div>
  <%= link_to 'Apply', "#", class:"btn btn-success btn-lg btn-applying"%>


<% if current_employer %>
  <%= link_to 'Edit', edit_job_path(@job), :class => 'link-move'  %>
  <%= link_to 'Back', jobs_path, :class => 'link-move'%>
<% else %>
  <%= link_to 'Back', jobs_path, :class => 'link-move' %>
<% end %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse navbar-default">

  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to image_tag("MajorLogo.png", alt:"logo", :class => "d-inline-block align-top logo"), root_path, class:"navbar-brand" %>

  <div class="navbar-collapse collapse justify-content-end">
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item"><%= link_to "Jobs", jobs_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Suggest", suggestions_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "My Profile", current_user, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Log out", user_logout_path, class:"nav-link" %></li>
      <% elsif current_bootcamp %>
        <li class="nav-item"><%= link_to "My Profile", current_bootcamp, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Jobs", jobs_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Log out", bootcamp_logout_path, class:"nav-link" %></li>
      <% elsif current_employer %>
        <li class="nav-item"><%= link_to "My Profile", current_employer, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Jobs", jobs_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Add New Job", post_job_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Log out", bootcamp_logout_path, class:"nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Log in", user_login_path, class:"nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Major</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class='container'>
  <h1>About Us</h1>

  <p>I'm going to create an app that will make money.</p>








</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Candidates you can trust.</h1>
    <p>An exclusive place to hire talented and trained entry-level employees in the tech and startup community.</p>
    <p><%= link_to "See Jobs", jobs_path, class:"btn btn-primary btn-lg"%></p>
  </div>
</div>

<div class="container">
  <div class="marketing row">
    <div class="col-md-4 marketing_inner">
      <%= image_tag('trophy.png', :class => 'marketing_images') %>
      <h2>Talent</h2>
      <p>We partner with bootcamps and coding schools all over the country to get the brightest and boldest graduates currently seeking jobs in the tech sector. Each graduate has gone through intense training and in depth learning.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4 marketing_inner">
      <%= image_tag('globe.png', :class => 'marketing_images') %>
      <h2>Network</h2>
      <p>With a huge network of highly qualified graduates we're positive hiring with Major is an investment. By being part of Major, your company will have exclusive access to network of marketers, developers, designers, account managers, and more!</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4 marketing_inner">
      <%= image_tag('graph.png', :class => 'marketing_images') %>
      <h2>Growth</h2>
      <p>Grow your team for success. Every company CEO knows their company is only as great as their team. The wrong team members can be detrimental to your company's success and waste of valuable capital. Use Major to hire the best team members.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>


<hr class="container">

<div class="cta_outer">
  <div class="container cta_inner">
    <h1>Get started today</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
       ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
       ullamco laboris </p>
    <%= link_to "See Jobs", jobs_path, class:"btn btn-success btn-lg"%>
  </div>
</div>

<hr>

<footer>
  <ul>
    <li>&copy; 2017 Major, Inc.</li>
    <li><%=link_to 'About', root_path%></li>
    <li><%=link_to 'Sign up', root_path%></li>
    <li><%=link_to 'FAQ', root_path%></li>
    <li><%=link_to 'Bootcamps', root_path%></li>
  </ul>
</footer>

</div>

app/views/pages/suggestions.html.erb
<h1>Your suggestions here</h1>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>